# Generated by Django 3.0.7 on 2020-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200801_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254), max_length=200, unique=True),
        ),
    ]
