# Generated by Django 3.0.7 on 2020-08-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200801_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ending',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='starting',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
