# Generated by Django 3.0.7 on 2020-08-10 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200810_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 13, 41, 51, 21594)),
        ),
    ]
