# Generated by Django 3.1 on 2020-08-14 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 21, 28, 7, 462407)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
